### ISSUE TITLE
你好，想问一下收录中有awk命令吗？

### ISSUE THREAD

**Issue by ming995** [man-pages-zh/man-pages-translation#7]
没有找到awk命令，感觉这个命令还是挺重要的，而且基本Linux发行版本中都会带

**Comment by hosiet** [comment]
当代 Linux 系统上没有真正的 awk，只有 awk 标准的兼容实现（和 vi 实际上不存在是同样道理）。请参考 GNU 的实现 gawk 和某个最小化的实现 mawk。
